**Imports**

In [14]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler,MaxAbsScaler,MinMaxScaler,OneHotEncoder,OrdinalEncoder
from sklearn.model_selection import KFold,cross_validate,train_test_split
from sklearn.linear_model import LinearRegression,LogisticRegression,RidgeClassifier
from sklearn.metrics import accuracy_score,mean_absolute_error,root_mean_squared_error,confusion_matrix,recall_score,f1_score,precision_score,classification_report
from sklearn.svm import SVR,SVC
from sklearn.ensemble import AdaBoostRegressor,AdaBoostClassifier,RandomForestClassifier,GradientBoostingClassifier
plt.style.use("fivethirtyeight")
import warnings
warnings.filterwarnings('ignore')

In [15]:
df=pd.read_csv("diabetes.csv")

*Explore data*

In [16]:
df.shape

(768, 9)

In [17]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    int64
 2   BloodPressure             768 non-null    int64
 3   SkinThickness             768 non-null    int64
 4   Insulin                   768 non-null    int64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB

In [18]:
df.head(10)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
5,5,116,74,0,0,25.6,0.201,30,0
6,3,78,50,32,88,31.0,0.248,26,1
7,10,115,0,0,0,35.3,0.134,29,0
8,2,197,70,45,543,30.5,0.158,53,1
9,8,125,96,0,0,0.0,0.232,54,1

In [19]:
df.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [20]:
df.duplicated().sum()

np.int64(0)

In [22]:
df.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='str')

In [23]:
df[df["Outcome"]==0]

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
1,1,85,66,29,0,26.6,0.351,31,0
3,1,89,66,23,94,28.1,0.167,21,0
5,5,116,74,0,0,25.6,0.201,30,0
7,10,115,0,0,0,35.3,0.134,29,0
10,4,110,92,0,0,37.6,0.191,30,0
...,...,...,...,...,...,...,...,...,...
762,9,89,62,0,0,22.5,0.142,33,0
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
767,1,93,70,31,0,30.4,0.315,23,0

In [24]:
df[df["Outcome"]==1]

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
2,8,183,64,0,0,23.3,0.672,32,1
4,0,137,40,35,168,43.1,2.288,33,1
6,3,78,50,32,88,31.0,0.248,26,1
8,2,197,70,45,543,30.5,0.158,53,1
...,...,...,...,...,...,...,...,...,...
755,1,128,88,39,110,36.5,1.057,37,1
757,0,123,72,0,0,36.3,0.258,52,1
759,6,190,92,0,0,35.5,0.278,66,1
761,9,170,74,31,0,44.0,0.403,43,1
766,1,126,60,0,0,30.1,0.349,47,1

*Analysis*

In [ ]:
df.corr()
corrs=df.corr()

In [ ]:
corrs

In [ ]:
sns.heatmap(corrs,cmap="viridis",annot=True,fmt="0.2f",linewidth=.9)

In [ ]:
sns.countplot(x="Outcome",data=df, facecolor=(0, 0, 0, 0),
    linewidth=5,
    edgecolor=sns.color_palette("BrBG", 2),saturation=.1,

)

In [ ]:
plt.figure(figsize=(6, 8))

splot=sns.countplot(x="Outcome",data=df,hue="Outcome")
for p in splot.patches:
 print(p)
 splot.annotate(format(p.get_height(), '.2f'), (p.get_x() + p.get_width() / 2., p.get_height()),  ha = 'center', va = 'center', xytext = (0, 10), textcoords = 'offset points')

plt.show()

In [ ]:
plt.figure(figsize=(6, 8))

splot=sns.countplot(y="Outcome",data=df,hue="Outcome")
for p in splot.patches:
 splot.annotate(format(p.get_height(), '.2f'), (p.get_x() + p.get_width() / 2., p.get_height()),  ha = 'center', va = 'center', xytext = (0, 10), textcoords = 'offset points')

plt.show()

In [ ]:
plt.figure(figsize=(6, 8))

splot=sns.countplot(y="Outcome",data=df,hue="Outcome")
for p in splot.patches:
 print(p)
 splot.annotate(format(p.get_width(), '.2f'), ( p.get_width(), p.get_y()+p.get_height()/2),  ha = 'center', va = 'center', xytext = (0, 10), textcoords = 'offset points')

plt.show()

In [ ]:
plt.Figure(figsize=(30,20))

plt.subplot(1,3,1)
plt.title("counter plot")
sns.countplot(x="Pregnancies",data=df)

plt.subplot(1,3,2)
plt.title("Distribution plot")
sns.displot(df["Pregnancies"])

plt.subplot(1,3,3)
plt.title("Box plot")
sns.boxplot(y=df["Pregnancies"])

plt.show

In [ ]:
sns.boxplot(df.Age)

# Create Model

In [28]:
x=df.drop("Outcome",axis=1)
y=df.Outcome

# Splite the Data

In [29]:
x_train,x_test,y_train,y_test=train_test_split(x,y,shuffle=True,random_state=42,test_size=0.2)

In [35]:
x_test.loc[355]

Pregnancies                   9.000
Glucose                     165.000
BloodPressure                88.000
SkinThickness                 0.000
Insulin                       0.000
BMI                          30.400
DiabetesPedigreeFunction      0.302
Age                          49.000
Name: 355, dtype: float64

In [32]:
y_test

668    0
324    0
624    0
690    0
473    0
      ..
355    1
534    0
344    0
296    1
462    0
Name: Outcome, Length: 154, dtype: int64

In [ ]:
model1=LogisticRegression()
model2=SVC()
model3=RandomForestClassifier(class_weight="balanced",n_estimators=200,n_jobs=-1)
model4=GradientBoostingClassifier()
model5=AdaBoostClassifier(n_estimators=100)
models=[model1,model2,model3,model4,model5]

In [ ]:
def cal(model):
    model.fit(x_train,y_train)
    preds=model.predict(x_test)
    accuracy=accuracy_score(preds,y_test)
    f1=f1_score(preds,y_test)
    recall=recall_score(preds,y_test)
    precision=precision_score(preds,y_test)
    print(model)
    print(f"recall is {recall} f1 is {f1} accuracy is {accuracy} precision is {precision} ")
    #print(classification_report(preds))

In [ ]:
for model in models:
    cal(model)

In [ ]:
! pip install imbalanced-learn

In [ ]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier

param_grid = {
    'n_estimators': [100, 200],
    'max_depth': [None, 10, 20],
    'min_samples_split': [2, 5],
    'min_samples_leaf': [1, 2],
    'bootstrap': [True, False]
}

grid_search = GridSearchCV(RandomForestClassifier(), param_grid=param_grid, cv=5)
grid_search.fit(x_train,y_train)

print("Best Parameters:", grid_search.best_params_)
print("Best score:", grid_search.best_score_)

In [ ]:
import pickle

In [ ]:
filename="diabetes_prediction.sav"
pickle.dump(model3,open(filename,"wb"))